name: Publish Lazy Init Group Spring Boot Starter Package

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  packages: write

jobs:
  publish-to-github-packages:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 코드 가져오기 (Checkout)
        uses: actions/checkout@v4
      
      - name: JDK 21 설치
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          
      - name: Gradle 캐시 설정
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('spring-boot-lazy-init-group/**/*.gradle*', 'spring-boot-lazy-init-group/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: gradlew 실행 권한 부여
        working-directory: spring-boot-lazy-init-group
        run: chmod +x ./gradlew
      
      - name: 태그 이름에서 버전 정보 추출 (e.g. v1.0.0 -> 1.0.0)
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Gradle로 GitHub Packages에 배포
        working-directory: spring-boot-lazy-init-group
        run: ./gradlew publish -Pversion=${{ env.VERSION_TAG }}
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
